{% set version = "0.3.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sctransform
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sctransform_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sctransform/sctransform_{{ version }}.tar.gz
  sha256: c08e56df05d64ed04ee53eb9e1d4d321da8aff945e36d56db1d5ceb1cd7e6e0b

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-future                   # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-magrittr                 # [build_platform != target_platform]
    - r-dplyr                    # [build_platform != target_platform]
    - r-matrixstats              # [build_platform != target_platform]
    - r-rcpparmadillo            # [build_platform != target_platform]
    - r-ggplot2                  # [build_platform != target_platform]
    - r-future.apply             # [build_platform != target_platform]
    - r-mass                     # [build_platform != target_platform]
    - r-gridextra                # [build_platform != target_platform]
    - r-matrix                   # [build_platform != target_platform]
    - r-reshape2                 # [build_platform != target_platform]
    - r-rlang                    # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-matrix
    - r-rcpp >=0.11.0
    - r-rcpparmadillo
    - r-dplyr
    - r-future
    - r-future.apply
    - r-ggplot2
    - r-gridextra
    - r-magrittr
    - r-matrixstats
    - r-reshape2
    - r-rlang
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-matrix
    - r-rcpp >=0.11.0
    - r-rcpparmadillo
    - r-dplyr
    - r-future
    - r-future.apply
    - r-ggplot2
    - r-gridextra
    - r-magrittr
    - r-matrixstats
    - r-reshape2
    - r-rlang

test:
  commands:
    - $R -e "library('sctransform')"           # [not win]
    - "\"%R%\" -e \"library('sctransform')\""  # [win]

about:
  home: https://github.com/ChristophH/sctransform
  license: GPL-3.0-only
  summary: A normalization method for single-cell UMI count data using a  variance stabilizing transformation. The transformation is based on a  negative binomial regression model with regularized parameters. As part of the same regression framework, this package also provides functions for batch correction, and data correction.
    See Hafemeister and Satija 2019  <doi:10.1101/576827> for more details.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: sctransform
# Type: Package
# Title: Variance Stabilizing Transformations for Single Cell UMI Data
# Version: 0.2.0
# Authors@R: person(given = 'Christoph', family = 'Hafemeister', email = 'chafemeister@nygenome.org', role = c('aut', 'cre'), comment = c(ORCID = '0000-0001-6365-8254'))
# Description: A normalization method for single-cell UMI count data using a  variance stabilizing transformation. The transformation is based on a  negative binomial regression model with regularized parameters. As part of the same regression framework, this package also provides functions for batch correction, and data correction. See Hafemeister and Satija 2019  <doi:10.1101/576827> for more details.
# URL: https://github.com/ChristophH/sctransform
# BugReports: https://github.com/ChristophH/sctransform/issues
# License: GPL-3 | file LICENSE
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.0.2)
# Imports: MASS, Matrix, methods, future, future.apply, ggplot2, reshape2, gridExtra, Rcpp
# LinkingTo: Rcpp (>= 0.11.0), RcppEigen
# Suggests: irlba, testthat
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-04-11 23:46:40 UTC; chafemeister
# Author: Christoph Hafemeister [aut, cre] (<https://orcid.org/0000-0001-6365-8254>)
# Maintainer: Christoph Hafemeister <chafemeister@nygenome.org>
# Repository: CRAN
# Date/Publication: 2019-04-12 12:32:38 UTC
