{% set version = "0.4.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sctransform
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sctransform_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sctransform/sctransform_{{ version }}.tar.gz
  sha256: f07fdf1875eea9b89a2d7bedc4bd542bf7da836b1defc1aaf687018053377a50

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-future                     # [build_platform != target_platform]
    - r-rcpp >=0.11.0              # [build_platform != target_platform]
    - r-magrittr                   # [build_platform != target_platform]
    - r-dplyr                      # [build_platform != target_platform]
    - r-matrixstats                # [build_platform != target_platform]
    - r-rcpparmadillo              # [build_platform != target_platform]
    - r-ggplot2                    # [build_platform != target_platform]
    - r-future.apply               # [build_platform != target_platform]
    - r-mass                       # [build_platform != target_platform]
    - r-gridextra                  # [build_platform != target_platform]
    - r-matrix >=1.5.0             # [build_platform != target_platform]
    - r-reshape2                   # [build_platform != target_platform]
    - r-rlang                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ compiler('fortran') }}    # [osx and arm64]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-matrix >=1.5.0
    - r-rcpp >=0.11.0
    - r-rcpparmadillo
    - r-dplyr
    - r-future
    - r-future.apply
    - r-ggplot2
    - r-gridextra
    - r-magrittr
    - r-matrixstats
    - r-reshape2
    - r-rlang
    - libblas
    - liblapack
  run:
    - r-base
    - r-mass
    - r-matrix >=1.5.0
    - r-rcpp >=0.11.0
    - r-rcpparmadillo
    - r-dplyr
    - r-future
    - r-future.apply
    - r-ggplot2
    - r-gridextra
    - r-magrittr
    - r-matrixstats
    - r-reshape2
    - r-rlang

test:
  commands:
    - $R -e "library('sctransform')"           # [not win]
    - "\"%R%\" -e \"library('sctransform')\""  # [win]

about:
  home: https://github.com/satijalab/sctransform
  license: GPL-3.0-only
  summary: A normalization method for single-cell UMI count data using a  variance stabilizing transformation. The transformation is based on a  negative binomial regression model with regularized parameters. As part of the same regression framework, this package also provides functions for batch correction, and data correction.
    See Hafemeister and Satija 2019  <doi:10.1101/576827> for more details.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
