appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: GcIMZkvMBsyCoFJJ3SemDCnrw6vDSXSrGxy94Odyb+UCnagiZoPW0f2yLxgN0J9ZfAELPvt8Jz5AmvnBRdWx9fgRGk5FKFxPpw1Kuzlr+lSO1QJDBxdGZtlQcjcxWGXferlIZSUN2Pn1VkiHkMuIZLbsJLGL/h9JcVqNfPcGqTJ+N412rCMRmXLRiqTVuoBewwDyoM9bDzKpYNr6cU+zDtD7Ftt5gDtD527limGBWeaC+qxPYuvke4I3KD3ccNNcnVrBr4vPSgCNVH88yFNB7zuHn893FBEtKpjRGX6CQyZz/N0fliMtvtcXxU3bsNvFYfQKjx6aZISRcd6uQrEYLSWUOZjtNFUoRi3+VPaB7g8rVnMjAeMcZqvdNUYg+KbS88M7+QayePPBkcPcXJhK93S9ltfYLtpkWiWJZ2m+CkJmnvVl5UpQ0jiEDPEQYJV/UNw46GEYuq/bTUoS0rbxe2mPZqf4bC2EVSDHzRFIk0CHJcH1osUlvXWcjEI5nvAIg0T2pYW5M6u7bsDTpLZ2kcPEQA2mK0icOCQMOpI4byjT9mp1HeF/1rVi1GKpqHfxWujU7StgGfeVKqlrFNaKOXSDjFX7f9F2TNWZaVrMr4X3H9K1KR9WZWjQuhpy9AaXvXzcIDwB+c741dbkoMgbuPb86JlBDAcI7vyzDMLhiEo=}
bot:
  automerge: true
